name: music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  file_picker: ^8.0.6
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/images/icon.png
  android: true
  ios: true

  android_12:
    color: "#002642"
    image: assets/images/icon.png
#Para gerar a Splash Screen: dart run flutter_native_splash:create
